export const EventCentreData = [
  {
    id: 1,
    name: "Protea Event Centre",
    location: "No 24 Lanre Awolokun Street",
    rating: 4,
    capacity: `200 - 500`,
    amount: "120000",
  },
  {
    id: 2,
    name: "Protea Event Centre",
    location: "No 24 Lanre Awolokun Street",
    rating: 4,
    capacity: `200 - 500`,
    amount: "120000",
  },
  {
    id: 3,
    name: "Protea Event Centre",
    location: "No 24 Lanre Awolokun Street",
    rating: 4,
    capacity: `200 - 500`,
    amount: "120000",
  },
  {
    id: 4,
    name: "Protea Event Centre",
    location: "No 24 Lanre Awolokun Street",
    rating: 4,
    capacity: `200 - 500`,
    amount: "120000",
  },
  {
    id: 5,
    name: "Protea Event Centre",
    location: "No 24 Lanre Awolokun Street",
    rating: 4,
    capacity: `200 - 500`,
    amount: "120000",
  },
  {
    id: 6,
    name: "Protea Event Centre",
    location: "No 24 Lanre Awolokun Street",
    rating: 4,
    capacity: `200 - 500`,
    amount: "120000",
  },
  {
    id: 7,
    name: "Protea Event Centre",
    location: "No 24 Lanre Awolokun Street",
    rating: 4,
    capacity: `200 - 500`,
    amount: "120000",
  },
  {
    id: 8,
    name: "Protea Event Centre",
    location: "No 24 Lanre Awolokun Street",
    rating: 4,
    capacity: `200 - 500`,
    amount: "120000",
  },
  {
    id: 9,
    name: "Protea Event Centre",
    location: "No 24 Lanre Awolokun Street",
    rating: 4,
    capacity: `200 - 500`,
    amount: "120000",
  },
  {
    id: 10,
    name: "Protea Event Centre",
    location: "No 24 Lanre Awolokun Street",
    rating: 4,
    capacity: `200 - 500`,
    amount: "120000",
  },
  {
    id: 11,
    name: "Protea Event Centre",
    location: "No 24 Lanre Awolokun Street",
    rating: 4,
    capacity: `200 - 500`,
    amount: "120000",
  },
  {
    id: 12,
    name: "Protea Event Centre",
    location: "No 24 Lanre Awolokun Street",
    rating: 4,
    capacity: `200 - 500`,
    amount: "120000",
  },

];
